import { QuizQuestion, Difficulty, Grade } from "./data";

export interface CSSubTopic {
  id: string;
  name: string;
  icon: string;
  minGrade: number;
}

export const csSubTopics: CSSubTopic[] = [
  { id: "html-css", name: "HTML & CSS", icon: "🌐", minGrade: 6 },
  { id: "python", name: "Python", icon: "🐍", minGrade: 7 },
  { id: "javascript", name: "JavaScript", icon: "⚡", minGrade: 8 },
  { id: "java", name: "Java", icon: "☕", minGrade: 9 },
  { id: "c-cpp", name: "C / C++", icon: "⚙️", minGrade: 9 },
  { id: "sql", name: "SQL", icon: "🗄️", minGrade: 9 },
  { id: "react", name: "React", icon: "⚛️", minGrade: 10 },
  { id: "nodejs", name: "Node.js", icon: "🟢", minGrade: 10 },
  { id: "data-structures", name: "Data Structures", icon: "📊", minGrade: 10 },
];

export function getCSSubTopicsForGrade(grade: Grade): CSSubTopic[] {
  return csSubTopics.filter((t) => grade >= t.minGrade);
}

// Questions by sub-topic (grade-independent — difficulty handles level)
export const csSubTopicQuestions: Record<string, QuizQuestion[]> = {
  "html-css": [
    { id: "html1", question: "What does HTML stand for?", options: ["Hyper Text Markup Language", "High Tech Modern Language", "Hyper Transfer Markup Language", "Home Tool Markup Language"], correctAnswer: 0, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "html2", question: "Which tag is used for the largest heading?", options: ["<h6>", "<h1>", "<heading>", "<head>"], correctAnswer: 1, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "html3", question: "Which tag creates a paragraph?", options: ["<para>", "<p>", "<text>", "<pg>"], correctAnswer: 1, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "html4", question: "Which attribute specifies the URL in <a> tag?", options: ["src", "link", "href", "url"], correctAnswer: 2, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "html5", question: "CSS stands for?", options: ["Computer Style Sheets", "Cascading Style Sheets", "Creative Style System", "Colorful Style Sheets"], correctAnswer: 1, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "html6", question: "Which CSS property changes text color?", options: ["font-color", "text-color", "color", "foreground"], correctAnswer: 2, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "html7", question: "Which tag is used to insert an image?", options: ["<image>", "<pic>", "<img>", "<photo>"], correctAnswer: 2, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "html8", question: "Which CSS property sets background color?", options: ["bgcolor", "background-color", "color-bg", "back-color"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "html9", question: "What does the <br> tag do?", options: ["Bold text", "Line break", "Border", "Brown color"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "html10", question: "Which selector targets class in CSS?", options: ["#classname", ".classname", "*classname", "@classname"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "html11", question: "Which CSS property makes text bold?", options: ["text-weight", "font-bold", "font-weight", "bold"], correctAnswer: 2, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "html12", question: "Which tag creates an ordered list?", options: ["<ul>", "<ol>", "<list>", "<dl>"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "html13", question: "What is the CSS box model order from inside to outside?", options: ["Margin, Border, Padding, Content", "Content, Padding, Border, Margin", "Padding, Content, Border, Margin", "Content, Border, Padding, Margin"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "html14", question: "Which CSS property creates flex layout?", options: ["display: block", "display: flex", "display: grid", "display: inline"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "html15", question: "What is a semantic HTML tag?", options: ["Any tag with a class", "Tags that describe their meaning", "Tags with inline styles", "Empty tags"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "html16", question: "Which CSS unit is relative to the root font size?", options: ["px", "em", "rem", "%"], correctAnswer: 2, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "html17", question: "What does position: absolute do?", options: ["Fixes to viewport", "Positions relative to nearest positioned ancestor", "Stays in normal flow", "Sticks on scroll"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "html18", question: "Which tag is used for table row?", options: ["<td>", "<th>", "<tr>", "<table>"], correctAnswer: 2, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "html19", question: "What is the purpose of the <meta> tag?", options: ["Create links", "Display images", "Provide metadata about the page", "Create forms"], correctAnswer: 2, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "html20", question: "Which CSS property controls element visibility without removing it from layout?", options: ["display: none", "visibility: hidden", "opacity: 0", "Both B and C"], correctAnswer: 3, xpReward: 20, subject: "cs", difficulty: "hard" },
  ],
  python: [
    { id: "py1", question: "Which keyword is used to define a function in Python?", options: ["function", "def", "func", "define"], correctAnswer: 1, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "py2", question: "How do you print 'Hello' in Python?", options: ["echo('Hello')", "print('Hello')", "console.log('Hello')", "printf('Hello')"], correctAnswer: 1, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "py3", question: "Which symbol is used for comments in Python?", options: ["//", "/*", "#", "--"], correctAnswer: 2, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "py4", question: "What is the output of 2 ** 3?", options: ["6", "8", "5", "9"], correctAnswer: 1, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "py5", question: "Which data type stores True/False?", options: ["int", "str", "bool", "float"], correctAnswer: 2, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "py6", question: "What does len() function do?", options: ["Calculates length", "Adds numbers", "Sorts a list", "Prints output"], correctAnswer: 0, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "py7", question: "Which loop runs a fixed number of times?", options: ["while", "for", "do-while", "repeat"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "py8", question: "How do you create a list in Python?", options: ["(1,2,3)", "[1,2,3]", "{1,2,3}", "<1,2,3>"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "py9", question: "What does input() function do?", options: ["Display output", "Take user input", "Import module", "Define variable"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "py10", question: "Which keyword handles exceptions?", options: ["catch", "except", "handle", "error"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "py11", question: "What is a dictionary in Python?", options: ["Ordered list", "Key-value pairs", "A string type", "A function"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "py12", question: "What does 'import' keyword do?", options: ["Exports data", "Includes a module", "Creates a class", "Defines a variable"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "py13", question: "What is a tuple?", options: ["Mutable sequence", "Immutable sequence", "Dictionary", "Set"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "py14", question: "What does list comprehension do?", options: ["Deletes a list", "Creates a list in one line", "Sorts a list", "Copies a list"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "py15", question: "What is __init__ in Python?", options: ["Destructor", "Constructor method", "Import statement", "Print function"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "py16", question: "What is a lambda function?", options: ["Named function", "Anonymous function", "Class method", "Module"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "py17", question: "What does pip install do?", options: ["Runs a script", "Installs a package", "Creates a file", "Deletes code"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "py18", question: "What is the output of 'Hello'[1]?", options: ["H", "e", "l", "Error"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "py19", question: "Which method adds to end of list?", options: ["add()", "insert()", "append()", "push()"], correctAnswer: 2, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "py20", question: "What is inheritance in Python?", options: ["Copying code", "A class inheriting from another class", "Importing modules", "Variable scope"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
  ],
  javascript: [
    { id: "js1", question: "Which keyword declares a variable in modern JS?", options: ["var", "let", "dim", "define"], correctAnswer: 1, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "js2", question: "How do you log to the console?", options: ["print()", "echo()", "console.log()", "log()"], correctAnswer: 2, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "js3", question: "What is the file extension for JavaScript?", options: [".java", ".js", ".jsx", ".jscript"], correctAnswer: 1, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "js4", question: "Which symbol is used for strict equality?", options: ["==", "===", "!=", "="], correctAnswer: 1, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "js5", question: "What is NaN?", options: ["Not a Number", "Null and Nothing", "No assigned Name", "New array Number"], correctAnswer: 0, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "js6", question: "What does JSON stand for?", options: ["JavaScript Object Notation", "Java Standard Object Notation", "JavaScript Online Notation", "Just Simple Object Notation"], correctAnswer: 0, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "js7", question: "Which method adds element to end of array?", options: ["append()", "push()", "add()", "insert()"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "js8", question: "What is a callback function?", options: ["A function that calls itself", "A function passed as argument", "A class method", "A constructor"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "js9", question: "What does 'typeof' operator return?", options: ["The value", "The data type as string", "The variable name", "Boolean"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "js10", question: "Which event fires when page loads?", options: ["onload", "onclick", "onchange", "onhover"], correctAnswer: 0, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "js11", question: "What is 'this' in JavaScript?", options: ["Current function", "Current object context", "Global variable", "A keyword for loops"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "js12", question: "What is a Promise?", options: ["A data type", "Object for async operations", "A loop", "A variable type"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "js13", question: "What does async/await do?", options: ["Creates classes", "Handles asynchronous code", "Defines variables", "Creates loops"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "js14", question: "What is closure?", options: ["Closing a file", "Function with access to outer scope", "End of program", "A data structure"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "js15", question: "What is the DOM?", options: ["Data Object Model", "Document Object Model", "Digital Output Module", "Document Order Method"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "js16", question: "Which method selects an element by ID?", options: ["getElement()", "getElementById()", "selectById()", "findById()"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "js17", question: "What is destructuring?", options: ["Deleting objects", "Unpacking values from arrays/objects", "Creating classes", "Error handling"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "js18", question: "What is the spread operator?", options: ["**", "...", "->", "=>"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "js19", question: "Which array method creates a new array by transforming each element?", options: ["filter()", "map()", "reduce()", "forEach()"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "js20", question: "What does 'use strict' do?", options: ["Enables strict type checking", "Enables strict mode for error catching", "Imports modules", "Creates classes"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
  ],
  java: [
    { id: "java1", question: "Java is which type of language?", options: ["Scripting", "Object-Oriented", "Markup", "Assembly"], correctAnswer: 1, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "java2", question: "Which keyword creates a class in Java?", options: ["struct", "class", "object", "define"], correctAnswer: 1, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "java3", question: "What does JVM stand for?", options: ["Java Virtual Machine", "Java Variable Manager", "Java Version Module", "Just Virtual Machine"], correctAnswer: 0, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "java4", question: "Which method is the entry point of a Java program?", options: ["start()", "main()", "run()", "init()"], correctAnswer: 1, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "java5", question: "Which data type stores whole numbers?", options: ["float", "String", "int", "boolean"], correctAnswer: 2, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "java6", question: "What is encapsulation?", options: ["Hiding internal details", "Inheriting properties", "Multiple forms", "Code reuse"], correctAnswer: 0, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "java7", question: "Which keyword is used for inheritance?", options: ["inherit", "extends", "super", "implements"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "java8", question: "What is polymorphism?", options: ["Single form", "Multiple forms of a method", "Data hiding", "Module import"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "java9", question: "Which collection stores unique elements?", options: ["ArrayList", "HashMap", "HashSet", "LinkedList"], correctAnswer: 2, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "java10", question: "What does 'static' keyword mean?", options: ["Instance-level", "Class-level", "Private", "Protected"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "java11", question: "What is an interface in Java?", options: ["A class", "A contract of methods", "A variable", "A package"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "java12", question: "What is the difference between == and .equals()?", options: ["Same thing", "== compares references, .equals() compares values", "== is faster", "No difference"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "java13", question: "What is an abstract class?", options: ["A fully implemented class", "A class that cannot be instantiated directly", "A static class", "A final class"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "java14", question: "What does 'final' keyword do?", options: ["Makes mutable", "Prevents modification/inheritance", "Creates instance", "Imports package"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "java15", question: "What is exception handling in Java?", options: ["Ignoring errors", "Managing runtime errors with try-catch", "Compiling code", "Printing output"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "java16", question: "What is a constructor?", options: ["A destructor", "Special method called when object is created", "A loop", "A variable"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "java17", question: "What is garbage collection?", options: ["Deleting files", "Automatic memory management", "Sorting data", "File handling"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "java18", question: "Which access modifier gives widest access?", options: ["private", "protected", "default", "public"], correctAnswer: 3, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "java19", question: "What is method overloading?", options: ["Same name, different parameters", "Same name, same parameters", "Different class", "Error handling"], correctAnswer: 0, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "java20", question: "What is a package in Java?", options: ["A variable", "A group of related classes", "A method", "A loop"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
  ],
  "c-cpp": [
    { id: "c1", question: "Who created the C language?", options: ["James Gosling", "Dennis Ritchie", "Guido van Rossum", "Bjarne Stroustrup"], correctAnswer: 1, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "c2", question: "Which header file is needed for printf()?", options: ["<iostream>", "<stdio.h>", "<math.h>", "<string.h>"], correctAnswer: 1, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "c3", question: "What does C++ add to C?", options: ["Functions", "Object-Oriented Programming", "Variables", "Loops"], correctAnswer: 1, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "c4", question: "Which symbol ends a statement in C?", options: [".", ":", ";", ","], correctAnswer: 2, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "c5", question: "What is a pointer?", options: ["A variable", "A variable storing memory address", "A function", "A loop"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "c6", question: "What does malloc() do?", options: ["Frees memory", "Allocates memory dynamically", "Prints output", "Reads input"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "c7", question: "What is a struct in C?", options: ["A function", "A user-defined data type", "A loop", "A pointer"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "c8", question: "Which operator dereferences a pointer?", options: ["&", "*", "->", "::"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "c9", question: "What is the scope resolution operator in C++?", options: [".", "->", "::", "&&"], correctAnswer: 2, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "c10", question: "What is a virtual function in C++?", options: ["A static function", "A function that can be overridden", "A private function", "A constructor"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "c11", question: "What is the difference between new and malloc?", options: ["Same thing", "new calls constructor, malloc doesn't", "malloc is faster", "new is for C only"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "c12", question: "What is a template in C++?", options: ["A class", "Generic programming feature", "A variable", "A macro"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "c13", question: "What is STL in C++?", options: ["Standard Template Library", "System Type Library", "Static Test Language", "Standard Test Logic"], correctAnswer: 0, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "c14", question: "What does 'cout' do in C++?", options: ["Takes input", "Outputs to console", "Creates file", "Allocates memory"], correctAnswer: 1, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "c15", question: "What is an array?", options: ["A single value", "Collection of same-type elements", "A function", "A class"], correctAnswer: 1, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "c16", question: "What is recursion?", options: ["A loop", "A function calling itself", "A variable", "An operator"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "c17", question: "What is operator overloading?", options: ["Using operator with different types", "Giving custom meaning to operators", "Error in code", "Multiple functions"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "c18", question: "What does sizeof() return?", options: ["Value of variable", "Size in bytes", "Address", "Type name"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "c19", question: "What is a reference in C++?", options: ["A pointer", "An alias for another variable", "A copy", "A constant"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "c20", question: "What is multiple inheritance?", options: ["One class inheriting from multiple classes", "One class used many times", "Nesting classes", "Abstract class usage"], correctAnswer: 0, xpReward: 20, subject: "cs", difficulty: "hard" },
  ],
  sql: [
    { id: "sql1", question: "What does SQL stand for?", options: ["Structured Query Language", "Simple Question Language", "Standard Query Logic", "System Query Language"], correctAnswer: 0, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "sql2", question: "Which command retrieves data?", options: ["INSERT", "DELETE", "SELECT", "UPDATE"], correctAnswer: 2, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "sql3", question: "Which keyword filters results?", options: ["FILTER", "WHERE", "HAVING", "FIND"], correctAnswer: 1, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "sql4", question: "Which command adds new data?", options: ["ADD", "INSERT INTO", "CREATE", "PUT"], correctAnswer: 1, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "sql5", question: "What is a PRIMARY KEY?", options: ["Any column", "Unique identifier for each row", "A foreign key", "An index"], correctAnswer: 1, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "sql6", question: "Which clause sorts results?", options: ["SORT BY", "ORDER BY", "GROUP BY", "ARRANGE BY"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "sql7", question: "What does JOIN do?", options: ["Deletes tables", "Combines rows from multiple tables", "Creates indexes", "Sorts data"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "sql8", question: "Which function counts rows?", options: ["SUM()", "COUNT()", "TOTAL()", "NUM()"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "sql9", question: "What does DISTINCT do?", options: ["Sorts data", "Removes duplicate values", "Adds data", "Creates table"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "sql10", question: "Which command modifies existing data?", options: ["MODIFY", "CHANGE", "UPDATE", "ALTER"], correctAnswer: 2, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "sql11", question: "What is a FOREIGN KEY?", options: ["Primary key of same table", "Reference to primary key of another table", "A unique column", "An auto-increment column"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "sql12", question: "What is normalization?", options: ["Adding redundancy", "Organizing data to reduce redundancy", "Deleting data", "Indexing"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "sql13", question: "What is a subquery?", options: ["A deleted query", "A query inside another query", "A stored procedure", "A trigger"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "sql14", question: "What does GROUP BY do?", options: ["Sorts rows", "Groups rows with same values", "Filters rows", "Joins tables"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "sql15", question: "Which type of JOIN returns all rows from both tables?", options: ["INNER JOIN", "LEFT JOIN", "FULL OUTER JOIN", "CROSS JOIN"], correctAnswer: 2, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "sql16", question: "What is an INDEX?", options: ["A table", "Data structure for fast retrieval", "A constraint", "A view"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "sql17", question: "What does DROP TABLE do?", options: ["Empties table", "Deletes table permanently", "Renames table", "Copies table"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "sql18", question: "What is a VIEW?", options: ["A table copy", "A virtual table from a query", "An index", "A trigger"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "sql19", question: "What does LIKE operator do?", options: ["Exact match", "Pattern matching", "Range check", "Null check"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "sql20", question: "What is ACID in databases?", options: ["A chemical", "Atomicity, Consistency, Isolation, Durability", "A programming language", "A data type"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
  ],
  react: [
    { id: "react1", question: "What is React?", options: ["A database", "A JavaScript library for UI", "A programming language", "An operating system"], correctAnswer: 1, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "react2", question: "What is JSX?", options: ["JavaScript XML", "Java Syntax Extension", "JSON eXtended", "JavaScript Extra"], correctAnswer: 0, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "react3", question: "What is a component?", options: ["A CSS style", "A reusable UI piece", "A database table", "A server"], correctAnswer: 1, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "react4", question: "What hook manages state?", options: ["useEffect", "useState", "useRef", "useMemo"], correctAnswer: 1, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "react5", question: "What are props?", options: ["Properties passed to components", "State variables", "CSS classes", "Event handlers"], correctAnswer: 0, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "react6", question: "What is the Virtual DOM?", options: ["The real DOM", "A lightweight copy of the DOM", "A database", "A CSS framework"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "react7", question: "What does useEffect do?", options: ["Manages state", "Handles side effects", "Creates refs", "Renders UI"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "react8", question: "How do you conditionally render in React?", options: ["if-else in JSX", "Ternary operator or &&", "switch in JSX", "for loop"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "react9", question: "What is the key prop used for?", options: ["Styling", "Identifying list items uniquely", "Event handling", "State management"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "react10", question: "What is state?", options: ["A prop", "Data that changes over time in a component", "A CSS property", "A route"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "react11", question: "What is useContext used for?", options: ["Routing", "Sharing data without prop drilling", "HTTP requests", "Animation"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "react12", question: "What is useMemo for?", options: ["State management", "Memoizing expensive computations", "Side effects", "Refs"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "react13", question: "What is React Router?", options: ["A state manager", "Client-side routing library", "A CSS framework", "A build tool"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "react14", question: "What is a custom hook?", options: ["A built-in hook", "A reusable function using hooks", "A component", "A prop"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "react15", question: "What does React.memo do?", options: ["Creates memos", "Prevents unnecessary re-renders", "Manages state", "Handles errors"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "react16", question: "What is lifting state up?", options: ["Moving state to a child", "Moving shared state to a common parent", "Deleting state", "Creating global state"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "react17", question: "What event handler handles clicks?", options: ["onHover", "onChange", "onClick", "onSubmit"], correctAnswer: 2, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "react18", question: "How do you render a list?", options: ["for loop in JSX", "array.map()", "while loop", "forEach()"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "react19", question: "What is useReducer?", options: ["A simpler useState", "Alternative to useState for complex state", "A routing hook", "A ref hook"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "react20", question: "What is Suspense in React?", options: ["An error boundary", "A component for lazy loading fallbacks", "A state hook", "A router"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
  ],
  nodejs: [
    { id: "node1", question: "What is Node.js?", options: ["A browser", "JavaScript runtime on server", "A database", "A CSS framework"], correctAnswer: 1, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "node2", question: "Which engine powers Node.js?", options: ["SpiderMonkey", "V8", "Chakra", "Rhino"], correctAnswer: 1, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "node3", question: "What is npm?", options: ["Node Package Manager", "New Program Module", "Node Process Monitor", "Network Protocol Manager"], correctAnswer: 0, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "node4", question: "Which module handles file operations?", options: ["http", "fs", "path", "url"], correctAnswer: 1, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "node5", question: "What is Express.js?", options: ["A database", "A web framework for Node.js", "A templating engine", "A test framework"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "node6", question: "What is middleware?", options: ["A database", "Function that processes requests between server and route", "A CSS tool", "A template"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "node7", question: "What does require() do?", options: ["Exports module", "Imports a module", "Creates file", "Deletes file"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "node8", question: "What is the event loop?", options: ["A for loop", "Mechanism handling async operations", "A timer", "A callback"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "node9", question: "What does process.env contain?", options: ["File paths", "Environment variables", "User data", "Package info"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "node10", question: "What is a REST API?", options: ["A database", "An architectural style for web services", "A programming language", "A CSS method"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "node11", question: "What is package.json?", options: ["Source code", "Project metadata and dependencies", "A database file", "A config for CSS"], correctAnswer: 1, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "node12", question: "What HTTP method retrieves data?", options: ["POST", "PUT", "GET", "DELETE"], correctAnswer: 2, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "node13", question: "What is callback hell?", options: ["An error", "Deeply nested callbacks", "A module", "A framework"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "node14", question: "What is clustering in Node.js?", options: ["Database grouping", "Running multiple instances", "CSS grouping", "File merging"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "node15", question: "What does res.json() do?", options: ["Reads JSON", "Sends JSON response", "Parses JSON", "Creates JSON file"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "node16", question: "What is MongoDB often used with Node.js for?", options: ["Styling", "NoSQL database", "Routing", "Testing"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "node17", question: "What is a stream in Node.js?", options: ["A variable", "Data handled in chunks", "A function", "A class"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "node18", question: "What does app.listen() do?", options: ["Creates file", "Starts server on a port", "Sends response", "Reads request"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "node19", question: "What is JWT?", options: ["JavaScript Web Token", "JSON Web Token", "Java Web Tool", "JSON Widget Template"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "node20", question: "What is CORS?", options: ["A database", "Cross-Origin Resource Sharing", "A protocol", "A routing method"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
  ],
  "data-structures": [
    { id: "ds1", question: "What is a data structure?", options: ["A programming language", "Way to organize and store data", "A database", "An algorithm"], correctAnswer: 1, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "ds2", question: "What is an array?", options: ["A tree", "Collection of elements in contiguous memory", "A linked list", "A graph"], correctAnswer: 1, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "ds3", question: "What is a stack?", options: ["FIFO structure", "LIFO structure", "Random access structure", "Graph structure"], correctAnswer: 1, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "ds4", question: "What is a queue?", options: ["LIFO structure", "FIFO structure", "Random access", "Tree structure"], correctAnswer: 1, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "ds5", question: "What is a linked list?", options: ["Array of pointers", "Elements connected via pointers", "A hash table", "A tree"], correctAnswer: 1, xpReward: 5, subject: "cs", difficulty: "easy" },
    { id: "ds6", question: "What is the time complexity of array access?", options: ["O(n)", "O(1)", "O(log n)", "O(n²)"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "ds7", question: "What is a binary tree?", options: ["Tree with any number of children", "Tree where each node has at most 2 children", "A linked list", "A stack"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "ds8", question: "What is a hash table?", options: ["A sorted array", "Key-value store using hash function", "A binary tree", "A queue"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "ds9", question: "What is BFS?", options: ["Binary First Search", "Breadth-First Search", "Best First Search", "Block First Search"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "ds10", question: "What is DFS?", options: ["Data First Search", "Depth-First Search", "Direct First Search", "Dynamic First Search"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "ds11", question: "What is the time complexity of binary search?", options: ["O(n)", "O(n²)", "O(log n)", "O(1)"], correctAnswer: 2, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "ds12", question: "What is a heap?", options: ["A sorted array", "Complete binary tree with heap property", "A hash table", "A linked list"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "ds13", question: "What is a graph?", options: ["A chart", "Collection of nodes and edges", "A tree only", "An array"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "ds14", question: "What is recursion?", options: ["A loop type", "A function calling itself", "An array method", "A data type"], correctAnswer: 1, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "ds15", question: "What is Big O notation?", options: ["A variable name", "Describes algorithm efficiency", "A data structure", "A sorting method"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "ds16", question: "Which sorting algorithm has O(n log n) average case?", options: ["Bubble Sort", "Selection Sort", "Merge Sort", "Insertion Sort"], correctAnswer: 2, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "ds17", question: "What is a BST?", options: ["Binary Search Tree", "Basic Sort Tree", "Binary Stack Tree", "Block Search Table"], correctAnswer: 0, xpReward: 10, subject: "cs", difficulty: "medium" },
    { id: "ds18", question: "What is dynamic programming?", options: ["Writing fast code", "Solving problems by breaking into overlapping subproblems", "Creating dynamic websites", "Memory allocation"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "ds19", question: "What is a trie?", options: ["A binary tree", "Tree for string storage/retrieval", "A hash table", "A graph"], correctAnswer: 1, xpReward: 20, subject: "cs", difficulty: "hard" },
    { id: "ds20", question: "What is the worst case of quicksort?", options: ["O(n)", "O(n log n)", "O(n²)", "O(log n)"], correctAnswer: 2, xpReward: 20, subject: "cs", difficulty: "hard" },
  ],
};
